### ISSUE TITLE
python3 icloud_bypass.py

### ISSUE THREAD

**Issue by anixable** [z3ven/icloud_bypasser#1]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/paramiko/transport.py", line 2113, in run
    self._check_banner()
  File "/usr/local/lib/python3.10/dist-packages/paramiko/transport.py", line 2296, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

Error reading SSH protocol banner

**Comment by z3ven** [comment]
do you have a checkrain jailbreak? Without jailbreak it can't bypass. If you cant jailbreak your phone with checkrain you can use ramdisk tool and mount filesystem. Use `with_ramdisk.py` script to bypass in ramdisk mode

**Comment by anixable** [comment]
when i excecute the ramdisk i receive this :  anix@anix-G551JW:~/Downloads/icloud_bypasser-main$ python3 with_ramdisk.py
Exception (client): Error reading SSH protocol banner
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/paramiko/transport.py", line 2292, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/packet.py", line 374, in readline
    buf += self._read_timeout(timeout)
  File "/usr/local/lib/python3.10/dist-packages/paramiko/packet.py", line 603, in _read_timeout
    raise EOFError()
EOFError
